const store={getItem:k=>JSON.parse(localStorage.getItem('bbp_preview_'+k)??'null'),setItem:(k,v)=>localStorage.setItem('bbp_preview_'+k,JSON.stringify(v))};
const messages=store.getItem('chat')??[{name:'沃尔古纳',is_user:false,mes:'0 楼开场白：雨中的村庄等待来客。',extra:{}}];
const events=new Map();const names=['CHAT_CHANGED','GENERATION_STARTED','GENERATION_ENDED','GENERATION_STOPPED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED'];
const ctx={chat:messages,characters:[{avatar:'preview.png',name:'沃尔古纳',description:'饥荒中的村庄，人物各有选择'}],characterId:0,chatId:'preview',chatMetadata:store.getItem('meta')??{},getCurrentChatId:()=>ctx.chatId,saveChat:async()=>store.setItem('chat',ctx.chat),saveMetadata:async()=>store.setItem('meta',ctx.chatMetadata),getRequestHeaders:()=>({'Content-Type':'application/json'}),accountStorage:store,libs:{localforage:store},eventTypes:Object.fromEntries(names.map(n=>[n,n])),eventSource:{on:(n,f)=>{if(!events.has(n))events.set(n,new Set());events.get(n).add(f);},removeListener:(n,f)=>events.get(n)?.delete(f)},extensionSettings:{},setExtensionPrompt:(_key,text)=>{ctx.injection=text;},generateRaw:async({prompt})=>{await new Promise(r=>setTimeout(r,650));if(prompt.includes('连接测试'))return '{"ok":true}';if(prompt.includes('最简短的作者沟通'))return JSON.stringify({questions:[{question:'这段村庄故事最想先关注什么？',example:'村民日常，以及他们如何渡过粮荒。'},{question:'开局希望用什么节奏？',example:'慢一些，让我自由调查，不安排必走路线。'}]});const kind=prompt.startsWith('复盘')?'experience':prompt.startsWith('只根据')?'guide':'world';return JSON.stringify({changes:[{op:'put',record:{id:'preview-'+kind,kind,title:kind==='world'?'粮食与下一步选择':kind==='guide'?'保留叙事呼吸':'减少同义重复',blocks:[{id:'preview-block-'+kind,text:kind==='world'?'村长需要三日口粮。若旅人拒绝护送粮车，他将向邻镇求助；邻镇可能要求秋收后的劳力回报。眼下只是意图，尚未结盟。':'适当留白，让对话与行动推动节奏；避免反复提醒已经建立的细节。'}],truth:kind==='world'?'intent':'guidance',status:'active',importance:'major'}}]});}};
globalThis.SillyTavern={getContext:()=>ctx};
const actualFetch=globalThis.fetch.bind(globalThis);
globalThis.fetch=async(url,options={})=>{const path=String(url);if(path.startsWith('/user/files/bbpresets-')){const data=store.getItem(path);return new Response(data?JSON.stringify(data):'',{status:data?200:404});}if(path==='/api/files/upload'){const {name,data}=JSON.parse(options.body);const decoded=new TextDecoder().decode(Uint8Array.from(atob(data),c=>c.charCodeAt(0)));store.setItem('/user/files/'+name,JSON.parse(decoded));return Response.json({path:'/user/files/'+name});}return actualFetch(url,options);};
function renderChat(){const chat=document.getElementById('chat');chat.replaceChildren();ctx.chat.forEach((m,i)=>{const row=document.createElement('div');row.className='mes';row.setAttribute('mesid',i);const text=document.createElement('div');text.className='mes_text';text.textContent=m.name+'：'+m.mes;row.append(text);chat.append(row);});}renderChat();
await import('../index.js');
document.getElementById('reply').onclick=async()=>{for(const f of events.get('GENERATION_STARTED')??[])f('normal');const n=ctx.chat.length;ctx.chat.push({name:'旅人',is_user:true,mes:'我先问问邻镇的条件 '+n,extra:{}});await globalThis.bbPresetsInterceptor([],40000,()=>{},'normal');document.getElementById('generation-status').textContent='正文已立即开始；注入 '+(ctx.injection?.length??0)+' 字符。';ctx.chat.push({name:'沃尔古纳',is_user:false,mes:'来使抖落衣上的雨水。邻镇也并不宽裕，但愿意先借出一车粮。 '+n,extra:{}});renderChat();for(const f of events.get('GENERATION_ENDED')??[])f('normal');};

// Token counting also emits STARTED in the real host, without a matching ENDED.
for(const f of events.get('GENERATION_STARTED')??[])f('normal',{},true);
document.getElementById('new-chat').onclick=async()=>{ctx.chatId='preview-'+Date.now();ctx.chatMetadata={};ctx.chat=[{name:'沃尔古纳',is_user:false,mes:'新故事的 0 楼开场白。',extra:{}}];renderChat();for(const f of events.get('CHAT_CHANGED')??[])f();document.getElementById('generation-status').textContent='已新建聊天';};
